### ISSUE TITLE
Homebrew syntax and sha1 warnings

### ISSUE THREAD

**Issue by earthflat** [KeckCAVES/homebrew-keckcaves#6]
Dears,

Since yesterday homebrew gives the following warnings for vrui and vrui-examples formulae. As you can see, they refer to syntax and depreciated sha1 issues. Concerning the sha1 to sha256 conversion information is provided here:
https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Checksum_Deprecation.md

Warning messages from homebrew when upgrading formulae

Warning: Calling 'depends_on :libpng' is deprecated!
Use 'depends_on "libpng"' instead.
/usr/local/Library/Taps/keckcaves/homebrew-keckcaves/vrui.rb:12:in `class:Vrui'

Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/keckcaves/homebrew-keckcaves/vrui-examples.rb:6:in `class:VruiExamplesBlueMarbleTex'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/keckcaves/homebrew-keckcaves/vrui-examples.rb:6:in `class:VruiExamplesBlueMarbleTex'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/keckcaves/homebrew-keckcaves/vrui-examples.rb:6:in `class:VruiExamplesBlueMarbleTex'

**Comment by jeremyboggs** [comment]
The sha1 deprecation is now an error in Homebrew 1.1.0. See https://github.com/Homebrew/homebrew-core/issues/6677

**Comment by softpunch** [comment]
A deprecation is an error?

Is it not possible to migrate the tap to SHA 256?

It's a relatively small change, 
and I think there are even scripts to automate it.
